#! /usr/bin/env bash

echo "=== delete bucket"

# check for check for bucket name
if [ -z "$1" ]; then
    echo "no bucket name provided"
    echo "Usage: $0 <bucket-name> [region]"
    exit 1
fi

BUCKET_NAME="$1"
REGION="us-east-2"  # Default to us-east-1 if no region specified

aws s3api delete-bucket \
 --bucket "$BUCKET_NAME"
 