#! /usr/bin/env bash

echo "=== delete bucket"

# check for check for bucket name
if [ -z "$1" ]; then
    echo "no bucket name provided"
    
    exit 1
fi

BUCKET_NAME="$1"

# https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3api/index.html
aws s3api list-objects-v2 \
--bucket $BUCKET_NAME